### ISSUE TITLE
クエリのdate_truncが正常に動作していない

### ISSUE THREAD

**Issue by ke9000** [lee-lab-kokkaidb/kokkai-db#5]
<img width="1392" alt="2019-07-01_10 53 50" src="https://user-images.githubusercontent.com/12986282/60406240-dd12da00-9bef-11e9-9837-e3e93070e711.png">

**Comment by mikuta0407** [comment]
2019/07/01 10:41時点
<img width="1392" alt="スクリーンショット 2019-07-01 10 41 23" src="https://user-images.githubusercontent.com/13357430/60407171-a55a6100-9bf4-11e9-9f5a-06ce9487ba6e.png">

デリミタを修正
<img width="1392" alt="スクリーンショット 2019-07-01 10 53 50" src="https://user-images.githubusercontent.com/13357430/60407177-ad1a0580-9bf4-11e9-9bb6-895a662051f5.png">

検索条件
<img width="1392" alt="スクリーンショット 2019-07-01 11 05 37" src="https://user-images.githubusercontent.com/13357430/60407181-b2775000-9bf4-11e9-85d3-b24d37cad92f.png">

ここまではいく｡合計を押すと死ぬ
<img width="1392" alt="スクリーンショット 2019-07-01 11 10 38" src="https://user-images.githubusercontent.com/13357430/60407222-e2265800-9bf4-11e9-92ba-c91d21926371.png">

**Comment by mikuta0407** [comment]
```SQL
SELECT count(*) as cnt FROM t_conf as a inner join t_conf_item as b on a.conf_id=b.conf_id and a.conf_dt = b.conf_dt inner join t_talker as c on b.talker_id=c.talker_id and a.conf_id = c.conf_id WHERE a.conf_dt BETWEEN '20110101' and '20110131' AND a.diet_tp != '' and c.parties = '民主党・無所属クラブ' and c.talker_name = '与謝野馨' and date_trunc('year', b.conf_dt) = '/01/01 00:00:00' AND( content like '%消費税%')
```

Warning: pg_query(): Query failed: ERROR: invalid input syntax for type timestamp with time zone: "/01/01 00:00:00" LINE 4: ... = '与謝野馨' and date_trunc('year', b.conf_dt) = '/01/01 00... ^ in /virtual/hongchun/public_html/db.php on line 60

```SQL
SELECT b.conf_id, b.conf_item_id, c.talker_name, c.parties, c.position, c.roles, a.conf_dt, (SELECT dict_name FROM t_dict WHERE dict_tp = 'SYS_TP' AND dict_code = a.sys_tp) as sys_tp, (SELECT dict_name FROM t_dict WHERE dict_tp = 'DIET_TP' AND dict_code = a.diet_tp) as diet_tp, (SELECT dict_name FROM t_dict WHERE dict_tp = 'CONF_TP' AND dict_code = a.conf_tp) as conf_tp, a.conf_title, a.conf_no, a.conf_seq, a.item_cnt, a.conf_len, b.cont_len, CASE WHEN char_length(b.content) > 1200 THEN substr(b.content,1,1200) || '…' ELSE b.content END as content FROM t_conf as a inner join t_conf_item as b on a.conf_id=b.conf_id and a.conf_dt = b.conf_dt inner join t_talker as c on b.talker_id=c.talker_id and a.conf_id = c.conf_id WHERE a.conf_dt BETWEEN '20110101' and '20110131' AND a.diet_tp != '' and c.parties = '民主党・無所属クラブ' and c.talker_name = '与謝野馨' and date_trunc('year', b.conf_dt) = '/01/01 00:00:00' AND( content like '%消費税%') ORDER BY conf_dt ASC, a.conf_no, a.conf_seq, b.conf_item_id LIMIT 20 OFFSET 0
```

Warning: pg_query(): Query failed: ERROR: invalid input syntax for type timestamp with time zone: "/01/01 00:00:00" LINE 21: ... = '与謝野馨' and date_trunc('year', b.conf_dt) = '/01/01 00... ^ in /virtual/hongchun/public_html/db.php on line 60

**Comment by ke9000** [comment]
```date_trunc(落とすdate要素, date型データ)```
最初に`/`がついているのが悪さしてそう？

**Comment by ke9000** [comment]
セッション取得できていないっぽい

https://github.com/lee-lab-kokkaidb/kokkai-db/blob/master/list_model.php#L181
https://github.com/lee-lab-kokkaidb/kokkai-db/blob/master/list_model.php#L187
